### Créer un site
POST http://localhost:8080/api/sites
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nom": "Bureau bordeaux",
  "adresse": "12 rue de leybardie",
  "ville": "Bordeaux",
  "surfaceTotale": 5000,
  "nbPlaces": 100,
  "typeBatiment": "BUREAU",
  "dureeVie": 50,
  "eElec": 900000,
  "eGaz": 400000,
  "nombreEmployes": 500,
  "nombrePostesTravail": 350,
  "materiaux": [
    { "materiauId": 1, "quantite": 4000 },
    { "materiauId": 2, "quantite": 400 },
    { "materiauId": 3, "quantite": 90 },
    { "materiauId": 4, "quantite": 200 }
  ],
  "employes": [
    {
      "nb": 350,
      "modeTravail": "SUR_SITE",
      "transports": [
        { "mode": "VOITURE_THERMIQUE", "distance": 15 },
        { "mode": "BUS", "distance": 10 }
      ]
    },
    {
      "nb": 100,
      "modeTravail": "HYBRIDE",
      "joursSite": 109,
      "transports": [
        { "mode": "TRAIN", "distance": 20 }
      ]
    },
    {
      "nb": 50,
      "modeTravail": "REMOTE"
    }
  ]
}

### Lister mes sites
GET http://localhost:8080/api/sites
Authorization: Bearer {{token}}

### Récupérer un site par ID
GET http://localhost:8080/api/sites/3
Authorization: Bearer {{token}}

### Modifier un site
PUT http://localhost:8080/api/sites/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nom": "Capgemini Rennes (modifié)",
  "adresse": "Rennes, Bretagne",
  "ville": "Rennes",
  "surfaceTotale": 12000,
  "nbPlaces": 308,
  "typeBatiment": "BUREAU",
  "dureeVie": 50,
  "eElec": 1840000,
  "eGaz": 960000,
  "nombreEmployes": 1800,
  "nombrePostesTravail": 1037,
  "materiaux": [
    { "materiauId": 1, "quantite": 8500 },
    { "materiauId": 2, "quantite": 850 },
    { "materiauId": 3, "quantite": 180 },
    { "materiauId": 5, "quantite": 45 }
  ],
  "employes": [
    {
      "nb": 1200,
      "modeTravail": "SUR_SITE",
      "transports": [
        { "mode": "VOITURE_THERMIQUE", "distance": 18 },
        { "mode": "METRO", "distance": 6 }
      ]
    },
    {
      "nb": 500,
      "modeTravail": "HYBRIDE",
      "joursSite": 109,
      "transports": [
        { "mode": "TRAIN", "distance": 30 }
      ]
    },
    {
      "nb": 100,
      "modeTravail": "REMOTE"
    }
  ]
}

### Supprimer un site
DELETE http://localhost:8080/api/sites/2
Authorization: Bearer {{token}}
